name: Asherah-Node-Cucumber

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.9.0    
    - name: Install node packages
      run: npm i
    - name: Run Cucumber
      run: ./run-tests.sh
